export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  GRACE_PERIOD = 'GRACE_PERIOD',
  PAUSED = 'PAUSED',
  REFUNDED = 'REFUNDED',
}
